/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/OtoOiJLrJiH
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { type Folder } from "@prisma/client";
import { Button } from "~/components/ui/button";
import { Input } from "~/components/ui/input";

import { AllFolders } from "./single-folder";

const folders = [
  { id: 1, name: "Documents" },
  { id: 2, name: "Downloads" },
  { id: 3, name: "Music" },
  { id: 4, name: "Videos" },
];

export function FileExplorer({ folders }: { folders: Folder[] }) {
  return (
    <div className="flex h-screen flex-col bg-background">
      <header className="sticky top-0 z-10 flex items-center gap-2 border-b bg-background px-4 py-3">
        <Button variant="ghost" size="icon" className="rounded-full">
          <MenuIcon className="h-5 w-5" />
          <span className="sr-only">Open menu</span>
        </Button>
        <div className="flex-1">
          <Input
            type="search"
            placeholder="Search files..."
            className="w-full rounded-full bg-muted px-4 py-2 text-sm"
          />
        </div>
        <Button variant="ghost" size="icon" className="rounded-full">
          <ListOrderedIcon className="h-5 w-5" />
          <span className="sr-only">Sort files</span>
        </Button>
      </header>
      <main className="flex-1 overflow-auto">
        <div className="grid gap-2 p-4">
          <div className="flex items-center justify-between">
            <div className="text-sm font-medium">
              <span className="text-muted-foreground">Location:</span>{" "}
              /Documents
            </div>
            <div className="flex items-center gap-2">
              <Button variant="ghost" size="icon" className="rounded-full">
                <UploadIcon className="h-5 w-5" />
                <span className="sr-only">Upload file</span>
              </Button>
              <Button variant="ghost" size="icon" className="rounded-full">
                <PlusIcon className="h-5 w-5" />
                <span className="sr-only">Create new</span>
              </Button>
            </div>
          </div>
          <div className="grid gap-2">
            <AllFolders folders={folders} />

            {/* <Link */}
            {/*   href="#" */}
            {/*   className="flex items-center gap-3 px-4 py-3 rounded-md bg-muted hover:bg-muted/50" */}
            {/*   prefetch={false} */}
            {/* > */}
            {/*   <FolderIcon className="w-6 h-6" /> */}
            {/*   <div className="flex-1 truncate">Documents</div> */}
            {/*   <ChevronRightIcon className="w-5 h-5 text-muted-foreground" /> */}
            {/* </Link> */}
            {/* <Link */}
            {/*   href="#" */}
            {/*   className="flex items-center gap-3 px-4 py-3 rounded-md bg-muted hover:bg-muted/50" */}
            {/*   prefetch={false} */}
            {/* > */}
            {/*   <FileIcon className="w-6 h-6" /> */}
            {/*   <div className="flex-1 truncate">report.pdf</div> */}
            {/*   <ChevronRightIcon className="w-5 h-5 text-muted-foreground" /> */}
            {/* </Link> */}
            {/* <Link */}
            {/*   href="#" */}
            {/*   className="flex items-center gap-3 px-4 py-3 rounded-md bg-muted hover:bg-muted/50" */}
            {/*   prefetch={false} */}
            {/* > */}
            {/*   <ImageIcon className="w-6 h-6" /> */}
            {/*   <div className="flex-1 truncate">vacation_photos.zip</div> */}
            {/*   <ChevronRightIcon className="w-5 h-5 text-muted-foreground" /> */}
            {/* </Link> */}
            {/* <Link */}
            {/*   href="#" */}
            {/*   className="flex items-center gap-3 px-4 py-3 rounded-md bg-muted hover:bg-muted/50" */}
            {/*   prefetch={false} */}
            {/* > */}
            {/*   <FileIcon className="w-6 h-6" /> */}
            {/*   <div className="flex-1 truncate">presentation.pptx</div> */}
            {/*   <ChevronRightIcon className="w-5 h-5 text-muted-foreground" /> */}
            {/* </Link> */}
            {/* <Link */}
            {/*   href="#" */}
            {/*   className="flex items-center gap-3 px-4 py-3 rounded-md bg-muted hover:bg-muted/50" */}
            {/*   prefetch={false} */}
            {/* > */}
            {/*   <FolderIcon className="w-6 h-6" /> */}
            {/*   <div className="flex-1 truncate">Photos</div> */}
            {/*   <ChevronRightIcon className="w-5 h-5 text-muted-foreground" /> */}
            {/* </Link> */}
            {/* <Link */}
            {/*   href="#" */}
            {/*   className="flex items-center gap-3 px-4 py-3 rounded-md bg-muted hover:bg-muted/50" */}
            {/*   prefetch={false} */}
            {/* > */}
            {/*   <FileIcon className="w-6 h-6" /> */}
            {/*   <div className="flex-1 truncate">invoice.xlsx</div> */}
            {/*   <ChevronRightIcon className="w-5 h-5 text-muted-foreground" /> */}
            {/* </Link> */}
          </div>
        </div>
      </main>
      <footer className="sticky bottom-0 z-10 flex items-center justify-between gap-2 border-t bg-background px-4 py-3">
        <Button variant="ghost" size="icon" className="rounded-full">
          <HomeIcon className="h-5 w-5" />
          <span className="sr-only">Home</span>
        </Button>
        <Button variant="ghost" size="icon" className="rounded-full">
          <FolderIcon className="h-5 w-5" />
          <span className="sr-only">Folders</span>
        </Button>
        <Button variant="ghost" size="icon" className="rounded-full">
          <UploadIcon className="h-5 w-5" />
          <span className="sr-only">Upload</span>
        </Button>
        <Button variant="ghost" size="icon" className="rounded-full">
          <SettingsIcon className="h-5 w-5" />
          <span className="sr-only">Settings</span>
        </Button>
      </footer>
    </div>
  );
}


function ChevronRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  );
}

function FileIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z" />
      <path d="M14 2v4a2 2 0 0 0 2 2h4" />
    </svg>
  );
}

function FolderIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z" />
    </svg>
  );
}

function HomeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>
  );
}

function ImageIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="3" rx="2" ry="2" />
      <circle cx="9" cy="9" r="2" />
      <path d="m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21" />
    </svg>
  );
}

function ListOrderedIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="10" x2="21" y1="6" y2="6" />
      <line x1="10" x2="21" y1="12" y2="12" />
      <line x1="10" x2="21" y1="18" y2="18" />
      <path d="M4 6h1v4" />
      <path d="M4 10h2" />
      <path d="M6 18H4c0-1 2-2 2-3s-1-1.5-2-1" />
    </svg>
  );
}

function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  );
}

function PlusIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  );
}

function SettingsIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  );
}

function UploadIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="17 8 12 3 7 8" />
      <line x1="12" x2="12" y1="3" y2="15" />
    </svg>
  );
}
